EXPENSE_CATEGORIES = [
    "Housing",
    "Utilities",
    "Food & Dining",
    "Transportation",
    "Insurance",
    "Healthcare",
    "Financial",
    "Debt Payments",
    "Savings",
    "Investments",
    "Taxes",
    "Lifestyle",
    "Shopping / Personal",
    "Entertainment",
    "Travel",
    "Education",
    "Gifts & Donations",
	"Grocery",
]